[UP-422] Example medication schedule document
unidoc/unipdf-examples pull request #220
Opened 2023-02-25 22:37 UTC by kellemNegasi

creates medication schedule document according to [UP-422](https://unidoc.atlassian.net/browse/UP-422)

2023-02-28 15:01 UTC, 3ace requested changes

2023-03-01 18:07 UTC, 3ace approved these changes
lgtm

2023-03-01 18:58 UTC, sampila approved these changes
Looks good to me

2023-03-05 07:55 UTC, adrg reviewed
Looks good. I left a couple of minor observations.

2023-03-05 07:55 UTC, adrg commented on templates/medication-schedule-report/templates/main.tpl
> +        <table-cell border-width-right="0.5" border-width-bottom="0.5" vertical-align="bottom" align="left" indent="0">
No need to specify the `align` attribute as `left` is the default.

2023-03-05 07:55 UTC, adrg commented on templates/medication-schedule-report/templates/main.tpl
> +    <table-cell border-width-left="0.5" border-width-bottom="0.5" vertical-align="top" rowspan="{{len .TimesOfTheDay}}">
No need to specify the `vertical-align` attribute as `top` is the default.

2023-03-05 07:55 UTC, adrg commented on templates/medication-schedule-report/templates/main.tpl
> +    <table-cell  border-width-bottom="1.5" vertical-align="bottom" align="left" indent="0">
No need to specify the `align` attribute as `left` is the default.

2023-03-05 07:55 UTC, adrg commented on templates/medication-schedule-report/templates/main.tpl
> +    <table-cell vertical-align="top">
No need to specify the `vertical-align` attribute as `top` is the default.

2023-03-05 07:55 UTC, adrg commented on templates/medication-schedule-report/pdf_medication_schedule.go
> +			"getColumnWidths": func(NumOfCols int, colWidth float64) string {
Please start variable names with lowercase letters: `NumOfCols` -> `numOfCols`.

2023-03-06 20:35 UTC, kellemNegasi commented
Thanks @adrg I have updated the PR according to your comments.

2023-03-07 13:21 UTC, adrg approved these changes
Looks good. Thank you for addressing the review points.

2023-03-07 14:45 UTC, sampila approved these changes
looks good to me

2023-03-07 19:31 UTC, merged