[Up-477] Optimization example - remove unused resources
unidoc/unipdf-examples pull request #229
Opened 2023-07-20 09:49 UTC by kellemNegasi

2023-07-20 13:12 UTC, gunnsth requested changes
Can you update the README also under compress/ folder?

2023-07-20 13:13 UTC, gunnsth commented
Maybe we should mention which filters are lossy vs lossless.  Removing unused resources is lossless for the most parts.

2023-07-28 23:46 UTC, gunnsth commented
@kellemNegasi can you update this and the other PR?  A new release of unipdf has just been published so this should be ready once updated.

2023-07-29 16:02 UTC, kellemNegasi commented
> @kellemNegasi can you update this and the other PR?  A new release of unipdf has just been published so this should be ready once updated.

Ok. I will do.

2023-07-31 08:24 UTC, kellemNegasi commented
> Maybe we should mention which filters are lossy vs lossless. Removing unused resources is lossless for the most parts.

@gunnsth I have tried to mention which filters are lossless on the README file. Can you check and see if I have to add or remove some filters to or from the list.

2023-07-31 20:20 UTC, gunnsth commented on compress/README.md
> +From the available filters `CleanFonts`, `CleanUnusedResources`, `CombineDuplicateStreams`, `CombineDuplicateDirectObjects`,`CombineDuplicateDirectObjects`, `CleanFonts` and `CompressStreams` enable
UseObjectStreams also
CombineIdenticalIndirectObjects also

Actually most of them are lossless except ImageUpperPPI and ImageQuality.

2023-08-01 10:17 UTC, gunnsth approved these changes
LGTM

2023-08-01 10:17 UTC, merged