[US-20] Update examples with new builtin helper functions
unidoc/unipdf-examples pull request #249
Opened 2024-04-26 09:15 UTC by kellemNegasi

2024-04-29 19:54 UTC, sampila requested changes
Overall looks good, added minor comment

2024-04-29 19:54 UTC, sampila commented on templates/bank-account-statement/pdf_bank_account_statement.go
> +	// common.SetLogger(common.NewConsoleLogger(common.LogLevelDebug))
Remove commented code

2024-04-30 04:22 UTC, 3ace commented
since the new helper function would be included a new unipdf release, I think this PR should be put in draft mode first. Otherwise this updated example would not working correctly.

After there's a new unipdf release, you could reopen the PR and don't forget to update dependency to use the latest unipdf version.

2024-05-02 16:27 UTC, sampila approved these changes
Looks good to me

2024-05-02 16:27 UTC, 3ace approved these changes
lgtm

2024-05-02 16:28 UTC, merged